#!/bin/bash

source "ppx/test/script/var"

$BSC -color never -ppx $PPX $SRC &> $SNAPSHOT

RESULT=$?

if [ $RESULT -eq 2 ]
then
  echo "Output written to $SNAPSHOT"
  exit 0
else
  echo "Something went wrong"
  exit 1
fi
