#!/bin/bash

source "test/script/var"

$BSC -color never -ppx $PPX $SRC &> $DEST

RESULT=$?

if [ $RESULT -eq 2 ]
then
  echo "Output written to $DEST"
  exit 0
else
  echo "Something went wrong"
  exit 1
fi
